---
- name: install updates
  tags: always
  apt:
    upgrade: dist
    update_cache: yes

- name: create user "{{ username }}"
  user:
    name: "{{ username }}"
    groups: root
    shell: /bin/bash

- name: add authorized key for user "{{ username }}"
  authorized_key:
    user: "{{ username }}"
    key: "{{ ssh_public_key }}"

- name: add sudoers file for "{{ username }}"
  copy:
    src: sudoer_{{ username }}
    dest: /etc/sudoers.d/{{ username }}
    owner: root
    group: root
    mode: 0440
  notify: restart_sshd

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
